#!/usr/bin/env bash
set -xe

echo "Stage 0: build Rust reference compiler"
cargo build --release --bin raptor

echo "Stage 1: first self-host (Rust -> Raptor IR -> native binary)"
# LLVM IR of the compiler generated by the Rust version
./target/release/raptor --compile -O3 -v ./selfhost/raptor.rp
cp ./build/raptor.ll ./bootstrap/raptor.ll
./bootstrap/bootstrap.sh

echo "Stage 2: second self-host (Raptor recompiles itself)"
# LLVM IR of the compiler generated by the Raptor version
./bootstrap/raptor ./selfhost/raptor.rp
cp ./build/raptor.ll ./bootstrap/raptor.ll
./bootstrap/bootstrap.sh

echo "Stage 3: Valgrind leak check on the fully self-hosted binary"
valgrind --leak-check=full ./bootstrap/raptor ./selfhost/raptor.rp

echo "Done"
