use std::rc::Rc;

use crate::{
    common::{
        errors::{ErrorSeverity, IError, MacroExpanderError},
        span::Span,
    },
    frontend::ast::{DeclaredType, FunctionDeclaration, Program},
};

macro_rules! macro_node {
    ($value:expr) => {
        crate::frontend::ast::Node {
            value: $value,
            span: crate::common::span::Span::default(),
        }
    };
}
pub(crate) use macro_node;

pub struct MacroExpander<'a> {
    pub(in crate::macro_expander) program: &'a mut Program,
    supported_derives: Vec<String>,
    pub errors: Vec<Box<dyn IError>>,
}

impl<'a> MacroExpander<'a> {
    pub fn new(program: &'a mut Program) -> Self {
        let supported_derives = vec!["Debug".to_owned(), "Json".to_owned(), "Clone".to_owned()];

        MacroExpander {
            program,
            supported_derives,
            errors: vec![],
        }
    }

    pub fn run(&mut self) {
        self.expand_derive_macros();
    }

    fn expand_derive_macros(&mut self) {
        let declared_types = self
            .program
            .declared_types
            .iter()
            .map(|(_, type_declaration)| type_declaration.value.clone())
            .collect::<Vec<_>>();

        for declared_type in declared_types {
            self.expand_derive_macros_of_type(&declared_type);
        }
    }

    fn expand_derive_macros_of_type(&mut self, declared_type: &DeclaredType) {
        let (type_name, derives) = match declared_type {
            DeclaredType::Enum(enum_declaration) => (enum_declaration.identifier.value.clone(), enum_declaration.derives.clone()),
            DeclaredType::Struct(struct_declaration) => (struct_declaration.identifier.value.clone(), struct_declaration.derives.clone()),
        };

        for derive in derives {
            let is_supported = self.supported_derives.iter().any(|supported_derive| supported_derive == &derive.value);

            if !is_supported {
                let available_derives = self.supported_derives.join(", ");

                self.errors.push(Box::new(MacroExpanderError::at(
                    ErrorSeverity::HIGH,
                    format!(
                        "Use of unsupported derive macro '{}' on type '{}'. Available derive macros: {}.",
                        derive.value, type_name, available_derives
                    ),
                    derive.span,
                )));

                continue;
            }

            if derive.value == "Debug" {
                self.derive_debug(declared_type, derive.span);
            } else if derive.value == "Json" {
                self.derive_json(declared_type, derive.span);
            } else if derive.value == "Clone" {
                self.derive_clone(declared_type, derive.span);
            }
        }
    }

    pub(in crate::macro_expander) fn insert_function(&mut self, function: FunctionDeclaration, derive_span: Span) {
        let function_name = function.identifier.value.clone();

        if self.program.functions.contains_key(&function_name) {
            self.errors.push(Box::new(MacroExpanderError::at(
                ErrorSeverity::HIGH,
                format!(
                    "Function '{}' conflicts with a function generated by a derive macro. \
                 Remove the manually declared function or remove the corresponding derive.",
                    function_name
                ),
                derive_span,
            )));

            return;
        }

        self.program.functions.insert(function_name, Rc::new(macro_node!(function)));
    }
}

pub fn to_snake_case(value: &str) -> String {
    value
        .chars()
        .enumerate()
        .map(|(i, c)| {
            if c.is_uppercase() && i > 0 {
                format!("_{}", c.to_lowercase())
            } else {
                c.to_lowercase().to_string()
            }
        })
        .collect()
}
