../target/release/raptor basic.rp
../target/release/raptor fib_speed.rp
../target/release/raptor fib.rp
../target/release/raptor file_io.rp
../target/release/raptor file.rp
../target/release/raptor file4.rp
../target/release/raptor functions.rp
../target/release/raptor indexes.rp
../target/release/raptor numbers.rp
../target/release/raptor primes.rp
../target/release/raptor vectors.rp
../target/release/raptor game-of-life.rp
../target/release/raptor tcp-server.rp