../target/release/tkom basic.rp
../target/release/tkom fib_speed.rp
../target/release/tkom fib.rp
../target/release/tkom file_io.rp
../target/release/tkom file.rp
../target/release/tkom file4.rp
../target/release/tkom functions.rp
../target/release/tkom indexes.rp
../target/release/tkom numbers.rp
../target/release/tkom primes.rp
../target/release/tkom vectors.rp
../target/release/tkom game-of-life.rp
../target/release/tkom tcp-server.rp